### 1. NumPy Basics

✅ Q1: Create a 1D NumPy array from a list [10, 20, 30, 40, 50].

✅ Q2: Generate a 1D array of numbers from 10 to 50.

✅ Q3: Create a 1D array of 20 zeros, ones, and a constant value (e.g., 7).

✅ Q4: Generate an array of even numbers from 2 to 20.

✅ Q5: Create a 3x3 identity matrix (diagonal of ones).

✅ Q6: Generate a random integer matrix of shape (4,4) with values between 1 and 100.

In [1]:
import numpy as np

In [2]:
# Solution Q1
li = [10,20,30,40,50]
arr = np.array(li)
print(li)
print(arr)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


In [3]:
# Solution Q2
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [4]:
# Solution Q3
arr = np.ones(20,dtype = int)
print(arr)
arr1 = np.zeros(20,dtype = int)
print(arr1)
arr2 = np.full(20,7,dtype = int)
print(arr2)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [5]:
# Solution Q4
arr = np.arange(2,20,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18]


In [6]:
# Solution Q5
arr = np.eye((3))
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# Solution for Q6
arr = np.random.randint(1,100,size = (4,4))
print(arr)

[[26 98 27 72]
 [76 57 23 35]
 [49 86 65 18]
 [34 71 89 74]]


### 2. Indexing & Slicing

✅ Q7: Extract the first three elements from arr = np.array([5, 10, 15, 20, 25]).

✅ Q8: Reverse a NumPy array [1, 2, 3, 4, 5].

✅ Q9: Extract all even numbers from arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).

✅ Q10: Extract the first two rows and last two columns from a (4,4) matrix.

✅ Q11: Replace all values less than 10 in an array with 0.

In [8]:
# Solution Q7
li = [5,10,15,20,25]
arr = np.array(li)
print(arr[:3])

[ 5 10 15]


In [9]:
# Solution Q8
arr = np.random.randint(20,size = 5)
print(arr)
print("After reversing array")
print(arr[::-1])

[ 2 14 19  7  5]
After reversing array
[ 5  7 19 14  2]


In [10]:
# Solution Q9
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
bool_even = arr %2 == 0
new_arr = arr[bool_even] # Only the true value will be taken as per the numpy array.
print(new_arr)

[2 4 6 8]


In [11]:
# Solution Q10
arr = np.random.randint(1,20,size = (4,4))
print(arr)
print("First two row of the array are : ")
print(arr[:][:2])
print("First two column of the array are : ")
print(arr[:,:2])


[[10  7 19  8]
 [10 12  1 11]
 [ 1 12 14  1]
 [ 4  3 12  4]]
First two row of the array are : 
[[10  7 19  8]
 [10 12  1 11]]
First two column of the array are : 
[[10  7]
 [10 12]
 [ 1 12]
 [ 4  3]]


In [12]:
#Solution Q11
arr = np.random.randint(1,20,size = 10)
print(arr)
bool_arr = arr < 10
new_arr = arr
new_arr[bool_arr] = 0
print(new_arr)

[19 10  2 18  9 17 15 17 15 14]
[19 10  0 18  0 17 15 17 15 14]


### 3. Shape & Reshaping

✅ Q12: Convert a 1D array of 9 elements into a 3x3 matrix.

✅ Q13: Flatten a (3,3) matrix into a 1D array.

✅ Q14: Reshape an array [1, 2, 3, ..., 16] into a 4x4 matrix.

✅ Q15: Add an extra dimension to a (3,3) array to make it 3D.

In [13]:
# Solution 12
arr = np.random.randint(1,20,size = 9)
print(arr)
new_arr = np.reshape(arr,(3,3))
print(new_arr)

[11 11 10  3 19 17  5  5  1]
[[11 11 10]
 [ 3 19 17]
 [ 5  5  1]]


In [14]:
# Solution 13
new_arr
ans = new_arr.flatten()
print(ans)

[11 11 10  3 19 17  5  5  1]


In [15]:
# Solution 14
li = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
arr = np.array(li)
new_arr = np.reshape(arr,(4,4))
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
# Solution 15
arr = np.random.randint(1, 20, size=(3, 3))

# Add an extra dimension along axis 0
new_arr = arr[np.newaxis, :, :]

print("Original Shape:", arr.shape)
print("New Shape:", new_arr.shape)
print("New 3D Array:\n", new_arr)

Original Shape: (3, 3)
New Shape: (1, 3, 3)
New 3D Array:
 [[[ 6  9  2]
  [10 18  6]
  [13 15  1]]]


### MATHEMATICAL OPERATIONS
✅ Q16: Perform element-wise addition of A = [1, 2, 3] and B = [4, 5, 6].

✅ Q17: Compute the dot product of two matrices:

python

A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

✅ Q18: Multiply a (3,3) array by a scalar value 5.

✅ Q19: Compute the sum, mean, and standard deviation of an array [4, 8, 15, 16, 23, 42].

✅ Q20: Replace all negative values in an array with 0.

In [17]:
# Solution Q16
A = [1,2,3]
B = [4,5,6]
A = np.array(A)
B = np.array(B)
print(A+B)

[5 7 9]


In [18]:
# Solution 17
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [19]:
# Solution 18
arr = np.random.randint(1,20,size = (3,3))
print(arr*5)

[[60 95  5]
 [70  5 35]
 [50 20 55]]


In [20]:
# Solution 19
arr = [4, 8, 15, 16, 23, 42]
arr = np.array(arr)
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

18.0
108
12.315302134607444


In [21]:
# Solution 20
arr = np.random.randint(-10,20,size = (3,3))
print(arr)
bool_arr = arr < 0 # setting the boolean array for the condition True or False
print(bool_arr)
new_arr = arr.copy() # Copy of original array
new_arr[bool_arr] = 0 # setting the true conditions to 0 as np array will only go through the True values.
print(new_arr)

[[14 -3 18]
 [11 -1 -4]
 [-6 -4 -3]]
[[False  True False]
 [False  True  True]
 [ True  True  True]]
[[14  0 18]
 [11  0  0]
 [ 0  0  0]]


### 🎲 5. Random Numbers & Statistical Operations

✅ Q21: Generate a (4,4) array of random integers between 1 and 50.

✅ Q22: Create an array of 5 random numbers from a normal distribution (mean=0, std=1).

✅ Q23: Find the minimum, maximum, and their indices in a (3,3) matrix.

✅ Q24: Sort an array [5, 3, 8, 1, 9, 2] in ascending order.

In [22]:
# Solution 21
arr = np.random.randint(1,50,size = (4,4))
print(arr)

[[31 10 48 10]
 [30 10 17 43]
 [ 4 39  7 46]
 [47 49 42 11]]


In [23]:
# Solution 22
arr = np.random.normal(loc=0,scale = 1,size = 5) # scale = standard deviation, loc = Mean of the distribution
print(arr)

[ 0.38426898 -2.59884403  1.51467438  0.43489301  0.53839381]


In [24]:
# Solution 23
arr = np.random.randint(1,20,size = (3,3))
print(arr)
print(np.min(arr),np.argmin(arr))
print(np.max(arr),np.argmax(arr))
# print(np.)

[[17 19 10]
 [ 3 17  1]
 [17 15 19]]
1 5
19 1


In [25]:
# Solution 24
arr = [5, 3, 8, 1, 9, 2]
arr = np.array(arr)
print(arr)
arr = np.sort(arr)
print(arr)

[5 3 8 1 9 2]
[1 2 3 5 8 9]


🔎 6. Boolean Indexing & Filtering

✅ Q25: Given an array [10, 20, 30, 40, 50], find values greater than 25.

✅ Q26: Find the indices where elements in [1, 2, 3, 4, 5] are even.

✅ Q27: Find elements in arr = np.array([5, -3, 7, -1, 9]) that are negative.

In [26]:
# Solution 25
arr = [10,20,30,40,50]
arr = np.array(arr)
bool_arr = arr > 25
new_arr = arr[bool_arr]
print(new_arr)

[30 40 50]


In [27]:
# Solution 26
arr = np.array([1,2,3,4,5])
bool_arr = arr %2 == 0
index = np.where(bool_arr)
print(index)

(array([1, 3], dtype=int64),)


In [28]:
# Solution 27
arr = np.array([5, -3, 7, -1, 9])
new_arr = arr[arr < 0]
new_arr

array([-3, -1])

### 📐 7. Linear Algebra with NumPy

✅ Q28: Compute the determinant of the following matrix:

A = np.array([[3, 4], [2, 1]])

✅ Q29: Compute the inverse of matrix A:

A = np.array([[1, 2], [3, 4]])

✅ Q30: Solve the system of equations using np.linalg.solve:

3x + 2y = 8  

4x - y = 10

In [29]:
# Solution 28
A = np.array([[3, 4], [2, 1]])
print(np.linalg.det(A))

-5.000000000000001


In [30]:
# Solution 29
A = np.array([[1,2],[3,4]])
ans = np.linalg.inv(A)
ans

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [31]:
# 3x + 2y = 8
# 4x - y = 10

A = np.array([
    [3,2],
    [4,-1]
])
B = np.array([8,10])
ans = np.linalg.solve(A,B)
ans

array([2.54545455, 0.18181818])

### 📁 8. File Handling (CSV & Binary Files)

✅ Q31: Read a CSV file into a NumPy array.

✅ Q32: Save an array [10, 20, 30] to a .txt file.

✅ Q33: Load a .npy file into NumPy and print its contents.

In [ ]:
# Read CSV file (assuming it has numerical values)
data = np.genfromtxt("data.csv", delimiter = ",", skip_header=1)

In [35]:
# Create a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save as a text file
np.savetxt("output.txt", arr)

In [38]:
# Create an array
arr = np.array([[10, 20, 30], [40, 50, 60]])

# Save it as 'data.npy'
np.save("data.npy", arr)

# Load the saved .npy file
loaded_arr = np.load("data.npy")

# Print the loaded array
print("Loaded Array:\n", loaded_arr)

Loaded Array:
 [[10 20 30]
 [40 50 60]]


### 🚀 9. Broadcasting & Advanced Operations

✅ Q34: Add a 1D array [1, 2, 3] to a 2D array [[4, 5, 6], [7, 8, 9]] using broadcasting.

✅ Q35: Subtract the mean of each row from the row itself in a (3,3) matrix.

✅ Q36: Compute the cumulative sum of an array [1, 2, 3, 4].

In [39]:
# Broadcasting allows NumPy to add the 1D array to each row of the 2D array without needing to explicitly repeat the 1D array.

# How Broadcasting Works:
# The 1D array is broadcasted across both rows of the 2D array. Essentially, it is added to each row element-wise.
# For example, for the first row, [4, 5, 6] + [1, 2, 3] = [5, 7, 9].

# Broadcasting Rules
# If the dimensions of the arrays are not the same, NumPy tries to expand the smaller array to match the larger one.
# The size of the dimensions must either be the same or one of them must be 1.

import numpy as np

# Define a 1D array
arr_1d = np.array([1, 2, 3])

# Define a 2D array
arr_2d = np.array([[4, 5, 6], [7, 8, 9]])

# Add 1D array to each row of 2D array using broadcasting
result = arr_2d + arr_1d

# Print the result
print("Result of Broadcasting:\n", result)

Result of Broadcasting:
 [[ 5  7  9]
 [ 8 10 12]]


In [40]:
# Explanation:
# Step 1: Calculate Row Means

# For the first row [4, 5, 6], the mean is (4+5+6)/ 3 = 5
# For the second row [7, 8, 9], the mean is (7+8+9)/3 = 8
# For the third row [10, 11, 12], the mean is (10+11+12)/3 = 11

# Step 2: Subtract the Mean from Each Element

# The first row after subtracting 5 becomes [(4-5), (5-5), (6-5)] = [-1, 0, 1].
# The second row after subtracting 8 becomes [(7-8), (8-8), (9-8)] = [0, 1, 2].
# The third row after subtracting 11 becomes [(10-11), (11-11), (12-11)] = [0, 1, 2].

import numpy as np

# Create a 3x3 matrix
arr = np.array([[4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12]])

# Calculate the mean of each row (axis=1 means row-wise operation)
row_mean = np.mean(arr, axis=1, keepdims=True)
print(row_mean)

# Subtract the row mean from each element of the respective row
result = arr - row_mean

# Print the result
print("Matrix after subtracting row means:\n", result)

# NOTE: The np.mean() function computes the mean for each row and returns an array of shape (3, 1). 
# This result is broadcasted across the original array so that each element of a row is subtracted by the respective row's mean.

[[ 5.]
 [ 8.]
 [11.]]
Matrix after subtracting row means:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [41]:
# Explanation:
# For the array [1, 2, 3, 4]:
# The first element is just 1, so the cumulative sum is [1].
# The second element is 1 + 2 = 3, so the cumulative sum becomes [1, 3].
# The third element is 1 + 2 + 3 = 6, so the cumulative sum becomes [1, 3, 6].
# The fourth element is 1 + 2 + 3 + 4 = 10, so the cumulative sum becomes [1, 3, 6, 10].

import numpy as np

# Define the array
arr = np.array([1, 2, 3, 4])

# Compute the cumulative sum
cumulative_sum = np.cumsum(arr)

# Print the result
print("Cumulative Sum:", cumulative_sum)

#  Additional Notes:
# You can apply np.cumsum() on multi-dimensional arrays as well, and specify the axis to compute cumulative sums along different dimensions.
# Example for a 2D array:
# arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
# cumulative_sum_2d = np.cumsum(arr_2d, axis=0)  # Cumulative sum along columns
# print(cumulative_sum_2d)

Cumulative Sum: [ 1  3  6 10]


### 💥 10. Challenge Questions (Advanced)

✅ Q37: Find the most frequent value in an array [1, 3, 2, 4, 1, 3, 1, 2, 2].

✅ Q38: Find the Euclidean distance between two vectors [1, 2, 3] and [4, 5, 6].

✅ Q39: Count the number of unique values in an array [1, 2, 2, 3, 3, 3, 4, 5].

✅ Q40: Implement a function that normalizes a NumPy array between 0 and 1.

In [42]:
# To find the most frequent value in an array, 
# you can use NumPy along with np.bincount() (for integer arrays) 
# or scipy.stats.mode().

import numpy as np

# Define the array
arr = np.array([1, 3, 2, 4, 1, 3, 1, 2, 2])

# Use np.bincount() to find the frequency of each element
counts = np.bincount(arr)

# Find the index of the most frequent value
most_frequent_value = np.argmax(counts)

# Print the result
print("Most frequent value:", most_frequent_value)

# Explanation:
# np.bincount() counts the occurrences of each non-negative integer in the array.
# The result for the array [1, 3, 2, 4, 1, 3, 1, 2, 2] is:
# [0, 3, 3, 2, 1]
# This means:
# 0 occurs 0 times.
# 1 occurs 3 times.
# 2 occurs 3 times.
# 3 occurs 2 times.
# 4 occurs 1 time.
# np.argmax() finds the index of the maximum value in the counts array. In this case, the most frequent value is 1 (index 1 has the maximum count of 3).

Most frequent value: 1


In [43]:
import numpy as np

# Define the two vectors
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute the Euclidean distance
distance = np.linalg.norm(A - B)

# Print the result
print("Euclidean distance:", distance)


Euclidean distance: 5.196152422706632


In [44]:
import numpy as np

# Define the array
arr = np.array([1, 2, 2, 3, 3, 3, 4, 5])

# Use np.unique() to get unique values and their counts
unique_values, counts = np.unique(arr, return_counts=True)

# Print the unique values and their counts
print("Unique values:", unique_values)
print("Counts of unique values:", counts)


Unique values: [1 2 3 4 5]
Counts of unique values: [1 2 3 1 1]


In [45]:
import numpy as np

# Function to normalize the array
def normalize_array(arr):
    # Min and max values of the array
    arr_min = np.min(arr)
    arr_max = np.max(arr)
    
    # Normalization formula
    normalized_arr = (arr - arr_min) / (arr_max - arr_min)
    
    return normalized_arr

# Example array
arr = np.array([2, 5, 8, 1, 9])

# Normalize the array
normalized_arr = normalize_array(arr)

# Print the result
print("Normalized Array:", normalized_arr)


Normalized Array: [0.125 0.5   0.875 0.    1.   ]
