In [1]:
import numpy as np

arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [2]:
arr = np.random.randint(1,20,size = 10)
new_arr = arr[arr %2 == 0]
print(new_arr)

[10  6 10 18]


In [3]:
arr = np.random.randint(1,20,size = (4,4))
print(arr)
print(arr[:2][:])
print(arr[:,2:])


[[ 9  9 16  4]
 [ 4 11 14  5]
 [18 18  9  1]
 [18  3 18 12]]
[[ 9  9 16  4]
 [ 4 11 14  5]]
[[16  4]
 [14  5]
 [ 9  1]
 [18 12]]


In [4]:
arr = np.random.randint(1,20,size = 10)
print(arr)
bool_arr = arr %2 == 0
print(np.where(bool_arr))
new_arr = arr[bool_arr]
print(new_arr)
print()

[15  3 15 13 19  8 13 14 10 17]
(array([5, 7, 8], dtype=int64),)
[ 8 14 10]



In [7]:
arr = np.random.randint(-20,20,size = 10)
print(arr)
new_arr = arr[arr < 0]
print(new_arr)

[ 14  -8 -14 -14  14 -13 -13  -3   1  19]
[ -8 -14 -14 -13 -13  -3]
